name: Common CI Workflow

on:
  workflow_call:
    inputs:
      deploy:
        type: boolean
        default: false
      fast-fail:
        type: boolean
        default: true


jobs:
  ubuntu-build:
    strategy:
      fail-fast: ${{ inputs.fast-fail }}
      matrix:
        os: ["ubuntu:18.04", "ubuntu:20.04", "ubuntu:22.04", "debian:bullseye"]
    secrets: inherit
    uses: ./.github/workflows/common-container.yml
    with:
      container: ${{ matrix.os }}
      deploy: ${{ inputs.deploy }}
      dependencies_command: 'apt update && apt install make gcc build-essential python3 python3-pip curl -y'

  ubuntu-build-arm:
    strategy:
      fail-fast: ${{ inputs.fast-fail }}
      matrix:
        os: ["ubuntu:18.04", "ubuntu:20.04", "ubuntu:22.04", "debian:bullseye"]
    secrets: inherit
    uses: ./.github/workflows/self-hosted-arm.yml
    with:
      container: ${{ matrix.os }}
      deploy: ${{ inputs.deploy }}
      dependencies_command: 'apt update && apt install make gcc build-essential python3 python3-pip curl -y'

  yum-flavors:
    strategy:
      fail-fast: ${{ inputs.fast-fail }}
      matrix:
        include:
          - os: "centos:centos7"
            osnick: "centos7"
          - os: "amazonlinux:2"
            osnick: "amazonlinux"
          - os: "rockylinux:8"
            osnick: "rockylinux"
    secrets: inherit
    uses: ./.github/workflows/common-container.yml
    with:
      container: ${{ matrix.os }}
      os-nickname: ${{ matrix.osnick }}
      deploy: ${{ inputs.deploy }}
      dependencies_command: 'yum install make gcc tar gzip curl python3 python3-devel -y'

  yum-flavors-arm:
    strategy:
      fail-fast: ${{ inputs.fast-fail }}
      matrix:
        include:
          - os: "centos:centos7"
            osnick: "centos7"
          - os: "amazonlinux:2"
            osnick: "amazonlinux"
          - os: "rockylinux:8"
            osnick: "rockylinux"
    secrets: inherit
    uses: ./.github/workflows/self-hosted-arm.yml
    with:
      container: ${{ matrix.os }}
      os-nickname: ${{ matrix.osnick }}
      deploy: ${{ inputs.deploy }}
      dependencies_command: 'yum install make gcc tar gzip curl python3 python3-devel -y'

  mac-build:
    strategy:
      fail-fast: ${{ inputs.fast-fail }}
      matrix:
        runners: [macos-12, ARM64]
    secrets: inherit
    uses: ./.github/workflows/common-runner.yml
    with:
      runner: ${{ matrix.runners }}
      deploy: ${{ inputs.deploy }}
