name: Publish

on:
  pull_request: # TEMP
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  UBUNTU_DEPS: 'apt update && apt install make gcc build-essential python3 python3-pip curl -y'
  YUM_DEPS: 'yum install make gcc tar gzip curl python3 python3-devel -y'

jobs:
  ubuntu-build:
    strategy:
      matrix:
        os: ["ubuntu:18.04", "ubuntu:20.04", "ubuntu:22.04", "debian:bullseye"]
    secrets: inherit
    uses: ./.github/workflows/common-container.yml
    with:
      container: ${{ matrix.os }}
      deploy: true
      dependencies_command: ${{ github.env.UBUNTU_DEPS }}

  ubuntu-build-arm:
    strategy:
      matrix:
        os: ["ubuntu:18.04", "ubuntu:20.04", "ubuntu:22.04", "debian:bullseye"]
    secrets: inherit
    uses: ./.github/workflows/self-hosted-arm.yml
    with:
      container: ${{ matrix.os }}
      deploy: true
      dependencies_command: ${{ github.env.UBUNTU_DEPS }}


  yum-flavors:
    strategy:
      matrix:
        include:
          - os: "centos:centos7"
            osnick: "centos7"
          - os: "amazonlinux:2"
            osnick: "amazonlinux"
          - os: "rockylinux:8"
            osnick: "rockylinux"
    secrets: inherit
    uses: ./.github/workflows/common-container.yml
    with:
      container: ${{ matrix.os }}
      deploy: true
      dependencies_command: ${{ github.env.YUM_DEPS }}

  yum-flavors-arm:
    strategy:
      matrix:
        include:
          - os: "centos:centos7"
            osnick: "centos7"
          - os: "amazonlinux:2"
            osnick: "amazonlinux"
          - os: "rockylinux:8"
            osnick: "rockylinux"
    secrets: inherit
    uses: ./.github/workflows/self-hosted-arm.yml
    with:
      container: ${{ matrix.os }}
      deploy: true
      dependencies_command: ${{ github.env.YUM_DEPS }}

  mac-build:
    strategy:
      matrix:
        runners: [macos-12]
    secrets: inherit
    uses: ./.github/workflows/common-runner.yml
    with:
      runner: ${{ matrix.runners }}
      python-setup: '3.10'
      deploy: true
