name: Publish


on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ubuntu-build:
    strategy:
      matrix:
        os: ["ubuntu:18.04", "ubuntu:20.04", "ubuntu:22.04", "debian:bullseye"]
    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    steps:
    - name: apt update
      run: apt-get update
    - name: Install deps
      run: apt-get install make gcc -y
    - uses: actions/checkout@v3
    - name: Make
      run: make

  yum-flavors:
    strategy:
      matrix:
        os: ["centos:centos7", "amazonlinux:2", "rockylinux:8"]
    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    steps:
    - name: Install deps
      run: yum install make gcc tar gzip -y
    - uses: actions/checkout@v3
    - name: Make
      run: make

  mac-build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Make
      run: make

# TODO: upload artifact to S3 under the following path
# https://s3.amazonaws.com/redismodules/rediscompat/rediscompat.Linux-ubuntu-x86_64.2.12.8
# https://s3.amazonaws.com/redismodules/rediscompat/rediscompat.OS-ARC-Version
