name: Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-deploy:
    uses: ./.github/workflows/common-flow.yml
    secrets: inherit
    with:
      deploy: true
      fast-fail: true
