name: Tests

on:
  pull_request:
    branches: [ "main" ]


jobs:
  ubuntu-build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu:18.04", "ubuntu:20.04", "ubuntu:22.04", "debian:bullseye"]
    secrets: inherit
    uses: ./.github/workflows/common-container.yml
    with:
      container: ${{ matrix.os }}
      dependencies_command: 'apt update && apt install make gcc build-essential python3 python3-pip curl -y'

  ubuntu-build-arm:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu:18.04", "ubuntu:20.04", "ubuntu:22.04", "debian:bullseye"]
    secrets: inherit
    uses: ./.github/workflows/self-hosted-arm.yml
    with:
      container: ${{ matrix.os }}
      deploy: true
      dependencies_command: 'apt update && apt install make gcc build-essential python3 python3-pip curl -y'

  yum-flavors:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "centos:centos7"
            osnick: "centos7"
          - os: "amazonlinux:2"
            osnick: "amazonlinux"
          - os: "rockylinux:8"
            osnick: "rockylinux"
    secrets: inherit
    uses: ./.github/workflows/common-container.yml
    with:
      container: ${{ matrix.os }}
      dependencies_command: 'yum install make gcc tar gzip curl python3 python3-devel -y'

  yum-flavors-arm:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "centos:centos7"
            osnick: "centos7"
          - os: "amazonlinux:2"
            osnick: "amazonlinux"
          - os: "rockylinux:8"
            osnick: "rockylinux"
    secrets: inherit
    uses: ./.github/workflows/self-hosted-arm.yml
    with:
      container: ${{ matrix.os }}
      dependencies_command: 'yum install make gcc tar gzip curl python3 python3-devel -y'

  mac-build:
    strategy:
      fail-fast: false
      matrix:
        runners: [macos-12]
    secrets: inherit
    uses: ./.github/workflows/common-runner.yml
    with:
      runner: ${{ matrix.runners }}
      python-setup: '3.10'
